name: AI Article Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'articles')

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            articles

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: articles/**

      - name: Review articles
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == articles/* ]]; then
              echo "$file のレビューを行います。"

              content=$(cat $file)
              word_count=$(echo "$content" | wc -w)
              if [ "$word_count" -gt 100 ]; then
                review=$(node ./scripts/claude_review.mjs $file)

                echo "$review" > review.json
                cat review.json

                summary=$(jq -r '.summary' review.json)
                structure=$(jq -r '.structure' review.json)
                details=$(jq -c '.details[]' review.json)

                gh pr comment $PR_URL --body "## 記事の要約
                $summary

                ## 構成に関するコメント
                $structure"

                for detail in $details; do
                  line=$(echo $detail | jq -r '.line')
                  comment=$(echo $detail | jq -r '.comment')
                  gh pr review $PR_URL --body "$comment" --comment --path $file --line $line
                done

                gh pr edit $PR_URL --body "$(gh pr view $PR_URL --json body --jq '.body') 

                ## 記事レビュー
                $summary

                $structure"
              else
                echo "記事の文字数が 100 未満のため、レビューを行いません。"
              fi
            fi
          done
