name: AI Article Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'articles')

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - uses: pnpm/action-setup@v2
        name: Setup Pnpm
        with:
          # version: XXX # If not specified, package.json#packageManager is used.
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: articles/**

      - name: Review articles
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == articles/* ]]; then
              echo "$file のレビューを行います。"

              content=$(cat $file)
              word_count=$(echo "$content" | wc -w)
              if [ "$word_count" -gt 100 ]; then
                review=$(node ./scripts/claude_review.mjs $file)

                echo "$review" > review.json
                cat review.json

                summary=$(jq -r '.summary' review.json)
                structure=$(jq -r '.structure' review.json)
                details=$(jq -c '.details[]' review.json)

                gh pr comment $PR_URL --body "## 記事の要約
                $summary

                ## 構成に関するコメント
                $structure"

                for detail in $details; do
                  line=$(echo $detail | jq -r '.line')
                  comment=$(echo $detail | jq -r '.comment')
                  gh pr review $PR_URL --body "$comment" --comment --path $file --line $line
                done

                gh pr edit $PR_URL --body "$(gh pr view $PR_URL --json body --jq '.body') 

                ## 記事レビュー
                $summary

                $structure"
              else
                echo "記事の文字数が 100 未満のため、レビューを行いません。"
              fi
            fi
          done
